config/routes.rb
Notificationv2::Application.routes.draw do
  resources :records
  #resources :users do |user|
  #  user.record_feed 'records/:token/feed.:format', :controller => 'records', :action => 'feed', :token => nil
  #end

  resources :groups
  resources :events

  resources :rules

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :path_prefix => 'd'
  #resources :users
  #devise_for :users
  resources :users, :only => [:show, :index, :edit, :update]
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :call_type, :ctc_id, :cust_no, :cust_region, :description, :entitlement_code, :group_owner, :milestone, :milestone_type, :other_text, :priority, :source, :terminate_flag, :ticket_id, :target_time, :time_stamp, :start_time
  has_and_belongs_to_many :rules

  after_create :add_event

  def add_event
    RULES_ENG.assert_event(self)
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  require 'notification'
  attr_accessible :title, :rule_ids, :user_ids
  has_many :rules
  has_and_belongs_to_many :users
  after_create :new_group_event_milestone

  def notify_group(group_id, message)
    msg = Notification.new
    msg.notify_group(group_id, message)
  end

  def new_group_event_milestone
    #create a system milestone
    @event = Event.new
    @event.call_type = "EVT"
    @event.ctc_id = ""
    @event.cust_no = ""
    @event.cust_region = CONFIG[:core_settings][:app_name].to_s
    @event.description = "New Group Created - #{self.title}"
    @event.entitlement_code = ""
    @event.group_owner = ""
    @event.milestone = "ESC"
    @event.milestone_type = "E"
    @event.other_text = "group creation"
    @event.priority = ""
    @event.source = CONFIG[:core_settings][:app_name].to_s
    @event.start_time = Time.now.utc
    @event.target_time = Time.now.utc
    @event.terminate_flag = "1"
    @event.ticket_id = Digest::SHA1.hexdigest(Time.now.to_s + self.id.to_s)
    @event.time_stamp = Time.now.utc
    @event.save
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :check_for_cancel, :only => [:create, :update]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    begin
      @group.users.find(current_user.id)
      @group.users.delete(current_user)

      respond_to do |format|
        if @group.update_attributes(params[:group])
          format.html { redirect_to groups_url, notice: 'Group was successfully removed.' }
          format.json { head :no_content }
        else
          format.html { redirect_to groups_url, notice: 'Error removing Group' }
          format.json { head :no_content }
        end
      end
    rescue
      @group.users.push(current_user)

      respond_to do |format|
        if @group.update_attributes(params[:group])
          format.html { redirect_to groups_url, notice: 'Group was successfully added.' }
          format.json { head :no_content }
        else
          format.html { redirect_to groups_url, notice: 'Error adding Group' }
          format.json { head :no_content }
        end
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def notify
    #TODO figure out how to do a notify against form data which is not a record update & change below to use a value from a text field
    @group.notify_group(params[:id], "message")

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Notification Sent.' }
      format.json { head :no_content }
    end
  end

  private
    def check_for_cancel
      unless params[:cancel].blank?
        redirect_to groups_url, :notice => "Changes discarded"
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => {:class => "form-horizontal"}) do |f| %>

<% if @group.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group
    from being saved:</h2>

  <ul>
    <% @group.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<fieldset>
  <legend><%= legend_text %></legend>
  <div class="control-group">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class => "input-xlarge" %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :rules, :class => "control-label" %>
    <div class="controls">
      <%= f.collection_select(:rule_ids, Rule.all, :id, :title, {:selected => @group.rule_ids}, {:multiple => "multiple", :readonly => false}) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :users, :class => "control-label" %>
    <div class="controls">
      <%= f.collection_select(:user_ids, User.all, :id, :email, {:selected => @group.user_ids}, {:multiple => "multiple", :readonly => false}) %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit "Save changes", {:class => "btn btn-primary"} %>
    <%= f.submit "Cancel", {:class => "btn", :name => :cancel} %>
  </div>
</fieldset>
<% end %>

app/views/groups/edit.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "Editing group"} %>

app/views/groups/index.html.erb
<h1>Subscription Groups</h1>
<p>Click Add & Remove to change your subscription groups</p>
<h3>My Groups</h3>
<% if current_user.groups.empty? %>
    No Groups Found<br>
    <br />
<% else %>
    <% current_user.groups.each do |group| %>
        <%= link_to '<Remove>', group, :method => :put %> <%= group.title %><br>
    <% end %>
<% end %>
<br />

<% if current_user.has_role? :user %>
    <h3>Available Groups</h3>
    <% @groups.each do |group| %>
        <% if not current_user.groups.include? group %>
            <%= link_to '<Add>', group, :method => :put %> <%=  group.title %><br>
        <% end %>
    <% end %>
<% end %>
<br />

<% if current_user.has_role? :admin %>
    <h3>All Groups</h3>
    <table>
    <tr>
        <th>Title</th>
        <th></th>
        <th></th>
    </tr>

    <% @groups.each do |group| %>
    <tr>
        <td><%= group.title %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Group', new_group_path, :class => "btn btn-primary" %>

    <div class="pagination">
    <%= will_paginate @groups %>
    <div class="page_info">
        <%= page_entries_info @groups %>
    </div>
    </div>
    <br/>
<% end %>
<div>
</div>

app/views/groups/new.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "New group"} %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-horizontal">
  <fieldset>
    <div class="control-group">
      <%= label_tag @group, "Title", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag @group, @group.title, :class => "input-xlarge uneditable-input" %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag @group, "Rules", :class => "control-label" %>
      <div class="controls">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
            </tr>
          </thead>
          <tbody>
          <% @group.rules.each do |rule| %>
            <tr>
                <td><%= link_to rule.title, rule %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag @group, "Users", :class => "control-label" %>
      <div class="controls">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
          <% @group.users.each do |user| %>
            <tr>
                <td><%= link_to user.name, user %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to 'Edit', edit_group_path(@group), :class => "btn btn-primary " %>
      <%= link_to 'Back', groups_path, :class => "btn" %>
    </div>
  </fieldset>
</div>