config/routes.rb
Notificationv2::Application.routes.draw do
  resources :records
  #resources :users do |user|
  #  user.record_feed 'records/:token/feed.:format', :controller => 'records', :action => 'feed', :token => nil
  #end

  resources :groups
  resources :events

  resources :rules

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :path_prefix => 'd'
  #resources :users
  #devise_for :users
  resources :users, :only => [:show, :index, :edit, :update]
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :email, :message, :source, :rule_id_ref, :boxcar_notify, :nma_notify, :nmwp_notify, :mobile_ph_notify, :im_notify, :email_notify, :salesforce_notify, :prowl_notify
  belongs_to :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  def feed
    @user = User.find(params[:user_id])
    @records = @user.records
    @token = params[:token]

    respond_to do |format|
      if @user.valid_authentication_token?(@token)
        format.rss { render :layout > false }
      else
        format.rss { render :nothing > true, :status > :forbidden }
      end
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record, :html => {:class => "form-horizontal"}) do |f| %>

<% if @record.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record
    from being saved:</h2>

  <ul>
    <% @record.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<fieldset>
  <legend><%= legend_text %></legend>

  <div class="form-actions">
    <%= f.submit "Save changes", {:class => "btn btn-primary"} %>
    <%= f.submit "Cancel", {:class => "btn", :name => :cancel} %>
  </div>
</fieldset>
<% end %>

app/views/records/edit.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "Editing record"} %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <!-- <td><%= link_to 'Show', record %></td> -->
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= link_to 'Destroy', record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "New record"} %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>