config/routes.rb
Notificationv2::Application.routes.draw do
  resources :records
  #resources :users do |user|
  #  user.record_feed 'records/:token/feed.:format', :controller => 'records', :action => 'feed', :token => nil
  #end

  resources :groups
  resources :events

  resources :rules

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :path_prefix => 'd'
  #resources :users
  #devise_for :users
  resources :users, :only => [:show, :index, :edit, :update]
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :title, :group_id, :group_owner, :source, :cust_no, :call_type, :priority, :entitlement_code, :milestone1_operator, :milestone1_value, :milestone1_time_value, :milestone1_time_value_denomination, :target_time_operator, :target_time_value, :target_time_value_denomination, :ctc_id_operator, :ctc_id_value, :other_text_operator, :other_text_value, :syntax_msg
  belongs_to :group
  has_many :events
  unless ( File.basename($0) == "rake" && ARGV.include?("db:migrate") )
    after_save :reload_rules_eng
  end

  validates_presence_of :group


  def reload_rules_eng
    RULES_ENG.rebuild_engine
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  include RulesHelper
  before_filter :check_for_cancel, :only => [:create, :update]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.paginate(:page => params[:page], :include => [:group])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/new
  # GET /rules/new.json
  def new
    @rule = Rule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to rules_url, notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @rule = Rule.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule = Rule.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  private
    def check_for_cancel
      unless params[:cancel].blank?
        redirect_to rules_url, :notice => "Changes discarded"
      end
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_for(@rule, :html => {:class => "form-horizontal"}) do |f| %>

<% if @rule.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule
    from being saved:</h2>

  <ul>
    <% @rule.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<fieldset>
  <legend><%= legend_text %></legend>
  <div class="control-group">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class => "input-xlarge" %>
      <p class="help-block"></p>
    </div>
  </div>

  <h3>Limits</h3>
  <div class="control-group">
    <%= f.label :source, :class => "control-label" %>
    <div class="controls">
      <%= f.radio_button :source, "REMEDY" %> Remedy
      <%= f.radio_button :source, "ZEN" %> Zenoss
      <%= f.radio_button :source, "OV" %> OpenView
      <%= f.radio_button :source, "AVAYA" %> Avaya
      <%= f.radio_button :source, CONFIG[:core_settings][:app_name].to_s %> <%= CONFIG[:core_settings][:app_name].to_s %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :cust_no, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :cust_no %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :call_type, :class => "control-label" %>
    <div class="controls">
      <%= f.select :call_type, [['All Types',''],['INC - Incident','INC'],['SVR - Service Request','SVR'],['OUT - Outage','OUT'],['CMG - Change Management','CMG'],['EVT - Event','EVT']] %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :priority, :class => "control-label" %>
    <div class="controls">
      <%= f.select :priority, [['All',''],['P1','1'],['P2','2'],['P3','3'],['P4','4'],['P5','5']] %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :group_owner, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :group_owner %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :entitlement_code, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :entitlement_code %>
      <p class="help-block"></p>
    </div>
  </div>

  <h3>Definition</h3>
  <div class="control-group">
    <%= f.label :Milestone, :class => "control-label" %>
    <div class="controls">
      <%= f.select :milestone1_operator, [['Not Used',''],['Equals','=']] %>
      <%= f.text_field :milestone1_value %>
      Duration/Value
      <%= f.text_field :milestone1_time_value %>
      <%= f.select :milestone1_time_value_denomination, [['Not Used',''],['Count','count'],['Hours','H'],['Days','D']] %>
      <p class="help-block"></p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :Time_to_Target, :class => "control-label" %>
    <div class="controls">
      <%= f.select :target_time_operator, [['Not Used',''],['Less Than','<']] %>
      <%= f.text_field :target_time_value %>
      <%= f.select :target_time_value_denomination, [['Not Used',''],['Hours','H'],['Days','D'],['Perc %','%']] %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :CTC_ID, :class => "control-label" %>
    <div class="controls">
      <%= f.select :ctc_id_operator, [['Not Used',''],['Equals','='],['Not Equals','!=']] %>
      <%= f.text_field :ctc_id_value %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :Other_text, :class => "control-label" %>
    <div class="controls">
      <%= f.select :other_text_operator, [['Not Used',''],['Equals','='],['Not Equals','!=']] %>
      <%= f.text_field :other_text_value %>
    </div>
  </div>

  <h3>Message</h3>
  <div class="control-group">
    <%= f.label :syntax_msg, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :syntax_msg %>
    </div>
  </div>

  <h3>Group</h3>
  <div class="control-group">
    <%= f.label :group, :class => "control-label" %>
    <div class="controls">
      <%= f.collection_select :group_id, Group.all, :id, :title, {:selected => @rule.group_id}, {:class => "input-xlarge"} %>
      <p class="help-block"></p>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit "Save changes", {:class => "btn btn-primary"} %>
    <%= f.submit "Cancel", {:class => "btn", :name => :cancel} %>
  </div>
</fieldset>
<% end %>

app/views/rules/edit.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "Editing rule"} %>

app/views/rules/index.html.erb
<h1>Listing rules</h1><br/>
<% if @rules.empty? %>
    No Rules Found
<% else %>
<table>
  <tr>
    <th>Rule Group</th>
    <th>Rule ID</th>
    <th>Title</th>
    <th>Message</th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.group.title %></td>
    <td><%= rule.id %></td>
    <td><%= rule.title %></td>
    <td><%= rule.syntax_msg %></td>
    <!-- <td><%= link_to 'Show', rule %></td> -->
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>
<br>
<br />
<%= link_to 'New Rule', new_rule_path, :class => "btn btn-primary" %>

<div class="pagination">
  <%= will_paginate @rules %>
  <div class="page_info">
    <%= page_entries_info @rules %>
  </div>
</div>
<br/>

app/views/rules/new.html.erb
<%= render :partial =>  'form', :locals => {:legend_text => "New rule"} %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>
<div class="form-horizontal">
  <fieldset>
    <div class="control-group">
      <%= label_tag @rule, "Title", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag @rule, @rule.title, :class => "input-xlarge uneditable-input" %>
      </div>
    </div>
    <div class="form-actions">
      <%= link_to 'Edit', edit_rule_path(@rule), :class => "btn btn-primary " %>
      <%= link_to 'Back', rules_path, :class => "btn" %>
    </div>

  </fieldset>
</div>