config/routes.rb
Notificationv2::Application.routes.draw do
  resources :records
  #resources :users do |user|
  #  user.record_feed 'records/:token/feed.:format', :controller => 'records', :action => 'feed', :token => nil
  #end

  resources :groups
  resources :events

  resources :rules

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :path_prefix => 'd'
  #resources :users
  #devise_for :users
  resources :users, :only => [:show, :index, :edit, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "#{CONFIG[:core_settings][:app_name].to_s}", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <% if current_user.has_role? :SystemAdmin %>
        <!-- example of how to case roles -->
        <li class="nav-header">System Administrator</li>
        <li <%= raw 'class="active"' if params[:controller].to_sym == :events %> > <%= link_to("Events", events_path) %></li>
        <li <%= raw 'class="active"' if params[:controller].to_sym == :users %> > <%= link_to("Users", users_path) %></li>
    <% end %>

    <% if current_user.has_role? :Admin %>
        <!-- example of how to case roles -->
        <li class="nav-header">Administrator</li>
        <li <%= raw 'class="active"' if params[:controller].to_sym == :rules %> > <%= link_to("Rules", rules_path) %></li>
        <li <%= raw 'class="active"' if params[:controller].to_sym == :rule_groups %> > <%= link_to("Groups", groups_path) %></li>
    <% end %>

    <li class="nav-header">Tasks</li>
    <% if current_user.has_role? :User %>
        <li><%= link_to "My Subscription Groups", groups_path %></li>
    <% end %>
    <li><%= link_to "My Notification Settings", edit_user_path(current_user.id) %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "#{CONFIG[:core_settings][:app_name].to_s}" %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style type="text/css">
         body {
             padding-top: 60px;
             padding-bottom: 40px;
         }

         .sidebar-nav {
             padding: 9px 0;
         }
    </style>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span3">
            <%= render 'layouts/sidebar' if user_signed_in? %>
          </div>
          <div class="span9">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <hr>
        <footer>
          <%= content_for?(:footer) ? yield(:footer) : content_tag(:p, "&copy; 2012 - VENTYX, an ABB Company", nil, false) %>
        </footer>
      </div>
    </div>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33537904-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
  </body>
</html>